# Generated by Django 4.0.1 on 2022-09-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_status', models.CharField(max_length=40)),
                ('realm_up', models.BooleanField()),
            ],
        ),
    ]
