# Generated by Django 4.0.1 on 2022-09-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realmstatus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realm',
            name='realm_status',
        ),
        migrations.RemoveField(
            model_name='realm',
            name='realm_up',
        ),
        migrations.AddField(
            model_name='realm',
            name='is_up',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realm',
            name='name',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realm',
            name='status',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
